version: "{build}"
branches:
  only:
  - RC_1_1
os: Visual Studio 2015
clone_depth: 1
environment:
  matrix:
  - compiler: msvc-9.0
    model: 32
    python: 1
    crypto: openssl

install:
- git submodule update --init --recursive
- if %compiler% == msvc-14.0 if defined crypto if not exist openssl-1.0.1p-vs2015.7z (
    echo downloading openssl-2015
    & appveyor DownloadFile "https://www.npcglib.org/~stathis/downloads/openssl-1.0.1p-vs2015.7z"
  )
- if %compiler% == msvc-14.0 if defined crypto (
    echo extracting openssl-2015
    & 7z x -oc:\ -aoa openssl-1.0.1p-vs2015.7z > nul
    & rename c:\openssl-1.0.1p-vs2015 openssl
    & copy c:\openssl\lib64\ssleay32MT.lib c:\openssl\lib64\ssleay32.lib
    & copy c:\openssl\lib64\libeay32MT.lib c:\openssl\lib64\libeay32.lib
    & copy c:\openssl\lib\ssleay32MT.lib c:\openssl\lib\ssleay32.lib
    & copy c:\openssl\lib\libeay32MT.lib c:\openssl\lib\libeay32.lib
  )
- if %compiler% == msvc-9.0 if defined crypto if not exist openssl-1.1.0f-vs2008.7z (
  echo downloading openssl-2008
  & appveyor DownloadFile "https://www.npcglib.org/~stathis/downloads/openssl-1.1.0f-vs2008.7z"
  )
- if %compiler% == msvc-9.0 if defined crypto (
    echo extracting openssl-2008
    & 7z x -oc:\ -aoa openssl-1.1.0f-vs2008.7z > nul
    & rename c:\openssl-1.1.0f-vs2008 openssl
    & copy c:\openssl\bin\libsslMD.dll c:\openssl\bin\libssl-1_1.dll
    & copy c:\openssl\bin\libcryptoMD.dll c:\openssl\bin\libcrypto-1_1.dll
  )
- set INCLUDE=C:\Build-OpenSSL_1_1_0-110-VC9-32-Jenkins\include\openssl;%INCLUDE%
- set LIB=C:\Build-OpenSSL_1_1_0-110-VC9-32-Jenkins\lib;%LIB%
- set VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin
- set PYTHON_PATH=C:\Python27
- set BOOST_ROOT=c:\Libraries\boost_1_63_0
- set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
- set OPENSSL_PATH=c:\openssl-1.1\bin
- echo %BOOST_ROOT%
- echo %BOOST_BUILD_PATH%
- set PATH=%BOOST_ROOT%;%VS_PATH%;%PYTHON_PATH%;%OPENSSL_PATH%;%BOOST_BUILD_PATH%\src\engine\bin.ntx86;%PATH%;
- python --version
- cd %BOOST_BUILD_PATH%\src\engine
- build.bat >nul
- cd %ROOT_DIRECTORY%

cache:
- openssl-1.0.1p-vs2015.7z
- openssl-1.1.0f-vs2008.7z

build_script:
# python binding
- cd %APPVEYOR_BUILD_FOLDER%\bindings\python
- call "c:\program files (x86)\microsoft visual studio 9.0\vc\bin\vcvars32.bat"
- if defined python (
  b2 libtorrent-link=static boost-link=static release toolset=msvc-9.0 optimization=space runtime-link=static link=static variant=release crypto=openssl include=C:\openssl\include openssl-version=1.1 linkflags=/LIBPATH:C:\openssl\lib -j2 --hash
  )

#test_script:

artifacts:
  - path: bindings\python\dist\*.msi
    name: python-binding-win32
